services:
  backend:
    build:
      context: ./backend
    container_name: rpg-world-map-backend
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
      - ./frontend/assets/maps:/app/frontend/assets/maps
    networks:
      - rpg_world_map

  frontend:
    build:
      context: ./frontend
    container_name: rpg-world-map-frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend/assets/maps:/usr/share/nginx/html/assets/maps:ro
    networks:
      - rpg_world_map

networks:
  rpg_world_map:
    name: rpg_world_map
